### ISSUE TITLE
Unable to try other password in login page

### ISSUE THREAD

**Issue by Temp9699** [suankularb-wittayalai-school/mysk-frontend#101]
**Describe the bug**
When I tried logging in with wrong password I was redirected to /th/learn/null after login and was immediately redirected to that same page after re-running
Some error messages also appear if you go to /account

**To Reproduce**

1. Log in using Gino's email
2. use birthday as the password
3. redirected to /th/learn/null with 404
4. Go to /account
5. See the error messages

**Expected behavior**
User should be able to try logging in with a different password

**Screenshots**

Screenshots from when I'm testing and a screenshot from visual studio code terminal

![mysk1](https://user-images.githubusercontent.com/67576074/200107892-ddbcf945-b9d4-4f94-8adb-db4455a962db.png)
![mysk2](https://user-images.githubusercontent.com/67576074/200107898-8a167d2e-9dc3-47cf-b4e4-47cd637d6987.png)
![mysk3](https://user-images.githubusercontent.com/67576074/200107915-63c7e90e-6030-4d2e-a117-cc98f13cfca3.png)

**Additional context**
Note: Since the bug remains after re-running I can't test what else results in the same bug but I'm guessing it would lead to the same result with other emails other than Gino's

**Comment by Jimmy-Tempest** [comment]
`birthdate` is no longer the default email password using the latest commits should have a different label in the password helper. However, the expected should be as you said not redirecting the user and allow them to retry using different password

**Comment by Jimmy-Tempest** [comment]
as for now you might want to reset the cookie to retry logging in to test other features

**Comment by SiravitPhokeed** [comment]
Have you updated packages on your end? It looks like you’re simultaneously logged in and not logged in at the same time which probably means Supabase is very confused.
I recommend you just use the [deployment](https://mysk-frontend-gd6yjjvo0-suankularb-developers.vercel.app/) created in every PR for QA to prevent local host issues like this.
