### ISSUE TITLE
Welcome page form is unstable

### ISSUE THREAD

**Issue by Jimmy-Tempest** [suankularb-wittayalai-school/mysk-frontend#109]
**Describe the bug**
There are multiple ways welcome page can error including validation does not update for teacher info, password validation does not allow button press, welcome does not update onboard data for known issues

**To Reproduce**

1. Go to 'beta.mysk.school'
2. Login as new teacher
3. Fill in form data
4. See one of the error randomly

**Expected behavior**
The form update the data and allow user to go through after finishing the form

**Comment by SiravitPhokeed** [comment]
It’s most likely not random. I reproduced a screenshot provided to me earlier today and that was just an issue with the citizen ID validator formula. I suspect it’s probably minor bugs that are definitely not random. I’d like you to provide more examples of this “randomness” so I can reproduce and fix them.
