### ISSUE TITLE
Schedule breaks when a Period exceeds Schedule boundaries

### ISSUE THREAD

**Issue by CursorWind** [suankularb-wittayalai-school/mysk-frontend#139]
**Describe the bug**
If the teacher creates a period or move a period in such a way that exceeds the Schedule edges, it just says error and it won't let them edit it back.

**To Reproduce**
1. Add subject, note that it needs to be a double-period subject
2. Click the left-most button + drag the subject to the right-most class schedule block

**Screenshots**
![image](https://user-images.githubusercontent.com/110537544/230721005-b7883690-236e-481a-9b53-9ee58149008f.png) This is what happens after the bug is performed. it will just show an error message and not allow edits, basically locking you from going in and editing it back.

**Comment by SiravitPhokeed** [comment]
Can you adhere more to the templates provided (in this case the Bug Report template)? Or at the very least provide step-by-step reproduction. I find it quite difficult to understand what the issue even is or how to reproduce it.

**Comment by CursorWind** [comment]
Steps to reproduce
1. Add subject, note that it needs to be a double-period subject
2. Click the left-most button + drag the subject to the right-most class schedule block
That's it though. I will try to work on it tmr night. I think its because there is no func to check event dragging the double subject

**Comment by SiravitPhokeed** [comment]
Before the move is saved to the database, there is a check to see if the new Period location overlaps with an existing Period. You can add more checks here.

https://github.com/suankularb-wittayalai-school/mysk-frontend/blob/95771e914d100a155a08b668979817fcdee8eedf/utils/backend/schedule/schedule.ts#L289-L312
