### ISSUE TITLE
Allergies field returns an empty chip box for each character typed.

### ISSUE THREAD

**Issue by pixelpxed** [suankularb-wittayalai-school/mysk-frontend#224]
### Before we begin

- [x] I have already searched the Issues page, and I am sure this bug report isn’t a duplicate.

### What happened?

<img width="1710" alt="Screenshot 2567-02-08 at 09 43 10" src="https://github.com/suankularb-wittayalai-school/mysk-frontend/assets/70499960/e0a8affc-d19a-4704-b815-249b3fe0a5aa">
The allergies input field will insert a blank chip box for each character typed, and pressing enter will select the chip.

### Steps to reproduce

1. Use a teacher or student account.
2. Navigate to the 'Account' tab, then type any character such as "ทางคนอย่างเธอ" in the allergies field
3. See the blank chip box that appears for each character.

### Version

0.8.12

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by SiravitPhokeed** [comment]
This looks like a ReSKCom issue, but I believe ReSKCom hasn’t been updated since we created this field. So either we haven’t noticed this issue since the feature’s inception, or we accidentally changed something relating to the field in MySK itself.

We’ll have to take another look at ReSKCom, though.

**Comment by SiravitPhokeed** [comment]
https://github.com/suankularb-wittayalai-school/sk-components/blob/b16da972af243a84ee1e51978f732c43aaed2605/packages/skcom-react/src/components/ChipField/index.tsx#L270-L286

This might be the trouble spot. `indexOf` returns -1 when the entry separator isn’t found, which in JavaScript is evaluated into true. As a result, `onNewEntry` is called every keystroke.
