### ISSUE TITLE
Class number

### ISSUE THREAD

**Issue by Jimmy-Tempest** [suankularb-wittayalai-school/mysk-frontend#52]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to know the class number of a student

**Describe the solution you’d like**
We have 2 options
1. create a new property for the classroom called `no_list` and have it default to an array of zeros of length 50 (`[0, 0, 0, ..., 0]`) and save the student user id to the index of the array i.e. `class.no_list[classno - 1]`.
2. doesn't create a new property and use `students` property as it is but generates the array of zeros first then fills in the ids

**Additional context**
We did not consider creating a property on student user themselves because the class number changes every year with the class but the student account never change so the solution proposed is more long term but might be more complicated

**Comment by SiravitPhokeed** [comment]
Can I have an example of what using each option looks like? Right now I’m not sure I understand.

**Comment by Jimmy-Tempest** [comment]
it would look the same but we either make a new property or not
if the array is 
`[2, 0, 0, 4, 5,,..]`
then student id 2 is number 1 in this class and for number that does not exist and 4 is number 4 and so on
